### PR TITLE
module kytos -> napps.kytos

### PR DESCRIPTION
**Pull request by cemsbr**
Now, doc can be compiled.

### CODE REVIEW

**Comment by cemsbr** [comment]
@diraol, thanks for reminding me about it. I updated _setup.py_ and did other things, too.

**Comment by diraol** [comment]
@cemsbr why did you removed the of_liveness napp? We haven't discussed this.

**Comment by beraldoleal** [comment]
@cemsbr next time, please lets discuss if we should remove or not a napp. I know that this was a good thing to do.

**Comment by cemsbr** [comment]
@diraol, the reason is in my last commit message:

- (...)
- Remove old liveness napp referencing non-existing classes that:
  - Break docs compilation (can't be imported without errors)
  - Will certainly confuse newcomers.

**Pull request merged**
