### PR TITLE
[stats] Add Flow info in flow list

### LINKED ISSUE #57: Output for chord diagram
Create output for kytos/kytos-admin-ui#37. Besides statistics in ../flows, also Flow.to_json()

### PR DESCRIPTION
**Pull request by cemsbr**
Close #57

Additional changes:
- Remove unused Description
- Refactoring, using controller instead of controller.switches attr

### CODE REVIEW

**Comment by macartur** [comment]
@cemsbr , the Description class  is used to update switch descriptions.

**Comment by cemsbr** [comment]
@macartur, thanks for the warning. At the time of my commit, there was no `update_description` in Switch.

**Comment by beraldoleal** [comment]
@cemsbr the commit is here ?

**Comment by cemsbr** [comment]
@beraldo, the commit is 9416ad8 and is in PR #23. This discussion is duplicated there.

**Pull request merged**
